apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: init
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: apps
    repoURL: "https://github.com/Dja111/apps-gitops"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      #syncOptions:
      #- ApplyOutOfSyncOnly: true