apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wein-service
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: weinservice
    repoURL: "registry-1.docker.io/dja111"
    targetRevision: 0.1.0-6cd002d2043f70833363bc1c1fbf85be2c812c18
    helm:
      releaseName: weinservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      #syncOptions:
      #- ApplyOutOfSyncOnly: true