apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wein-service
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: weinservice
    repoURL: "registry-1.docker.io/dja111"
    targetRevision: 0.1.0-07691af425402379e4b37dffee3cde8af0126291
    helm:
      releaseName: weinservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      #syncOptions:
      #- ApplyOutOfSyncOnly: true